#!/usr/bin/env python3
"""Embed the brain's golden fixtures into a C header for the firmware
conformance test (test/native/test_conformance).

The fixtures in `e-drum brain/tests/fixtures/*.jsonl` are byte-frozen — the
executable specification of the session-file format and the firmware's
acceptance suite (phase0-plan, "Golden fixtures"). This script is the single
bridge: it reads them and emits string literals, so the expected bytes in the
firmware test are provably the brain's bytes, not a hand-copied approximation.

Run from the e-drummer directory:
    python tools/gen_fixture_header.py

Regenerate only if the fixtures ever legitimately change (which is a corpus
format break and should basically never happen).
"""

from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
FIXTURES = HERE.parent.parent / "e-drum brain" / "tests" / "fixtures"
OUT = HERE / "test" / "native" / "test_conformance" / "fixtures_data.h"

# Only the producible fixtures: `truncated` (torn tail) and `forward_compat`
# (unknown record types) exercise the READER, which is brain-side.
NAMES = {
    "minimal": "kFixtureMinimal",
    "declarations": "kFixtureDeclarations",
    "warmup_no_grid": "kFixtureWarmupNoGrid",
    "anonymous_enroll": "kFixtureAnonymousEnroll",
}


def c_literal_lines(data: bytes) -> list[str]:
    if b"\r" in data:
        raise SystemExit("fixture contains CR — fixtures are LF-only by contract")
    out = []
    for line in data.decode("utf-8").split("\n")[:-1]:
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        for ch in esc:
            if not (0x20 <= ord(ch) < 0x7F):
                raise SystemExit(f"non-ASCII byte in fixture line: {line!r}")
        out.append(f'    "{esc}\\n"')
    return out


def main() -> None:
    parts = [
        "// GENERATED by tools/gen_fixture_header.py from the brain's byte-frozen",
        "// golden fixtures (e-drum brain/tests/fixtures). DO NOT EDIT BY HAND.",
        "#pragma once",
        "",
    ]
    for stem, ident in NAMES.items():
        path = FIXTURES / f"{stem}.jsonl"
        data = path.read_bytes()
        parts.append(f"static const char {ident}[] =")
        parts.extend(c_literal_lines(data))
        parts.append(";")
        parts.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
